### ISSUE TITLE
add() function in linked-list.js

### ISSUE THREAD

**Issue by gabivlj** [amejiarosario/dsa.js#8]
In the add() function in [linked-list.js](https://github.com/amejiarosario/dsa.js/blob/master/src/data-structures/linked-lists/linked-list.js) I see the following line of code: 
`if (current.next) { current.next.previous = newNode; } // <7>`
What is the reason behind this line of code? If we are inserting behind current, I don't know why would you set the current.next.previous to the node we wanna insert. 

https://github.com/amejiarosario/dsa.js/blob/cc1ccc0183ea5d4675815413b7d1d4cc14da348c/src/data-structures/linked-lists/linked-list.js#L83-L105

**Comment by amejiarosario** [comment]
The short answer is... You need to update `current.next.previous` because it needs to point to the newly created node.

---

The long answer is...

I'll use the example on the [docs](https://github.com/amejiarosario/dsa.js/blob/master/book/chapters/linked-list.adoc#inserting-element-at-the-middle-of-the-list) to explain this line better. 



Let's say we have the following linked list:

```
art -> dog -> cat
```

and we want to insert a node called "new" on the position `1` (middle of the list).

https://github.com/amejiarosario/dsa.js/blob/cc1ccc0183ea5d4675815413b7d1d4cc14da348c/src/data-structures/linked-lists/linked-list.js#L92

So, `current` would be `dog` node, since is the one currently on position 1.

After we create the "new" element, to add it to the middle of the list we need to update 4 links
1. `new.previous`
2. `new.next`
3. `art.next`
4. `dog.previous`

[image](https://user-images.githubusercontent.com/418605/56431315-3f1d9d80-6297-11e9-8148-2026afa41cf4.png)

![image](https://user-images.githubusercontent.com/418605/56429689-d08a1100-6291-11e9-90ef-7ca71c2bc37e.png)

In code, it looks like this:
https://github.com/amejiarosario/dsa.js/blob/cc1ccc0183ea5d4675815413b7d1d4cc14da348c/src/data-structures/linked-lists/linked-list.js#L92-L99

So after we create the node,  we need to update 4 references:

1. Update node link `new.previous`: https://github.com/amejiarosario/dsa.js/blob/cc1ccc0183ea5d4675815413b7d1d4cc14da348c/src/data-structures/linked-lists/linked-list.js#L95

1. Update node link `new.next`: https://github.com/amejiarosario/dsa.js/blob/cc1ccc0183ea5d4675815413b7d1d4cc14da348c/src/data-structures/linked-lists/linked-list.js#L96

1. Update node link `art.next`: https://github.com/amejiarosario/dsa.js/blob/cc1ccc0183ea5d4675815413b7d1d4cc14da348c/src/data-structures/linked-lists/linked-list.js#L98

1. Update node link `dog.previous`: https://github.com/amejiarosario/dsa.js/blob/cc1ccc0183ea5d4675815413b7d1d4cc14da348c/src/data-structures/linked-lists/linked-list.js#L99

**Comment by amejiarosario** [comment]
@gabivlj Let me know if that explanation makes sense or if you still have doubts. I might add it to the main docs if this helps understanding.

**Comment by gabivlj** [comment]
Shouldn’t it be current.previous = newNode instead of current.next.previous = newNode?

**Comment by amejiarosario** [comment]
@gabivlj You are totally right! It should be `current.previous = newNode`. I'll update the code/docs/tests
